# This is a basic workflow to help you get started with Actions
#  Zit1 code personal fuer jede Tabellenkalkulation/backup
name: github

# Controls when the workflow will run
on: python  ipconfig -U -8.8.8.8  -localhost
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: python -8.8.8.8
    branches: [ "main","code" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
python -ipconfig -8.8.8.8 -proxy  python -python  -U -localhost  -U -8.8.8.8
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: python 8.8.8.8
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04/stable

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: python -print
        run: echo http://github.com/zitt-creator/

      # Runs a set of commands using the runners shell
      - name: python -print
        run: | 666.6.6.6
        
